// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzflutter pub add firebase_coreaSyB7pcAY_z4oZ8-N1kzsodT6opP21-uxx-8',
    appId: '1:17030672438:web:967ae6d99c232f56236897',
    messagingSenderId: '17030672438',
    projectId: 'segurity-information-app',
    authDomain: 'segurity-information-app.firebaseapp.com',
    storageBucket: 'segurity-information-app.firebasestorage.app',
    measurementId: 'G-NZKL5SJ93F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyb-dG9zWyTud0Vn8cdYCewYNUJbwtgDw',
    appId: '1:17030672438:android:81ca27b38661369a236897',
    messagingSenderId: '17030672438',
    projectId: 'segurity-information-app',
    storageBucket: 'segurity-information-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiX6ZeoPBzc3iCEEgQWjCxf3TeeDig7J8',
    appId: '1:17030672438:ios:ae31f2bb33ed5d37236897',
    messagingSenderId: '17030672438',
    projectId: 'segurity-information-app',
    storageBucket: 'segurity-information-app.firebasestorage.app',
    iosBundleId: 'com.Softgenix.seguridadFlutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiX6ZeoPBzc3iCEEgQWjCxf3TeeDig7J8',
    appId: '1:17030672438:ios:ae31f2bb33ed5d37236897',
    messagingSenderId: '17030672438',
    projectId: 'segurity-information-app',
    storageBucket: 'segurity-information-app.firebasestorage.app',
    iosBundleId: 'com.Softgenix.seguridadFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7pcAY_z4oZ8-N1kzsodT6opP21-uxx-8',
    appId: '1:17030672438:web:2017ec04f021482b236897',
    messagingSenderId: '17030672438',
    projectId: 'segurity-information-app',
    authDomain: 'segurity-information-app.firebaseapp.com',
    storageBucket: 'segurity-information-app.firebasestorage.app',
    measurementId: 'G-807SS485G9',
  );
}
